package install

import (
	"os"
	"strings"
)

func opencodePluginInstalled(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	content := string(b)
	return strings.Contains(content, piManagedExtensionMarker) && strings.Contains(content, "HitchPlugin") && strings.Contains(content, "dispatchToHitch")
}

func installOpenCodePlugin(path, backup, apiURL string) error {
	content, err := opencodePluginContent(apiURL)
	if err != nil {
		return err
	}
	return installExtensionContent(path, backup, content)
}

func opencodePluginContent(apiURL string) ([]byte, error) {
	return openCodePluginContent("opencode", "hitch-opencode-plugin", opencodeHookEvents, apiURL)
}

func openCodePluginContent(harnessName, clientVersion string, sourceEvents []string, apiURL string) ([]byte, error) {
	urlLiteral, err := jsonStringLiteral(apiURL)
	if err != nil {
		return nil, err
	}
	eventsLiteral, err := jsonArrayLiteral(sourceEvents)
	if err != nil {
		return nil, err
	}
	harnessLiteral, err := jsonStringLiteral(harnessName)
	if err != nil {
		return nil, err
	}
	versionLiteral, err := jsonStringLiteral(clientVersion)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.Grow(5000 + len(piManagedExtensionMarker) + len(urlLiteral) + len(eventsLiteral) + len(harnessLiteral) + len(versionLiteral))
	b.WriteString("// ")
	b.WriteString(piManagedExtensionMarker)
	b.WriteString(`.
// Generated by hitch-client install. Do not edit by hand.

const HITCH_PINNED_API_URL = `)
	b.WriteString(urlLiteral)
	b.WriteString(`;
const HITCH_DEFAULT_API_URL = "http://127.0.0.1:8799";
const HITCH_EVENTS = `)
	b.WriteString(eventsLiteral)
	b.WriteString(`;

function envString(name) {
  const processLike = typeof globalThis === "object" ? Object(globalThis).process : undefined;
  const env = processLike && typeof processLike === "object" ? Object(processLike).env : undefined;
  const value = env && typeof env === "object" ? Object(env)[name] : undefined;
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.length > 0) return value;
    if (typeof value === "number" && Number.isFinite(value)) return String(value);
  }
  return undefined;
}

function hitchAPIURL() {
  return firstString(HITCH_PINNED_API_URL, envString("HITCH_URL"), HITCH_DEFAULT_API_URL);
}

function safeClone(value) {
  if (value === undefined) return {};
  try {
    return JSON.parse(JSON.stringify(value));
  } catch {
    return {};
  }
}

function modelString(model) {
  if (typeof model === "string") return model;
  if (!model || typeof model !== "object") return undefined;
  const provider = firstString(model.providerID, model.providerId, model.provider, model.vendor);
  const id = firstString(model.modelID, model.modelId, model.id, model.model, model.name);
  if (provider && id) return provider + "/" + id;
  return id || provider;
}

function eventSessionID(event) {
  return firstString(event?.sessionID, event?.session_id, event?.properties?.sessionID, event?.properties?.session_id);
}

function collectMetadata(input, event, ctx) {
  const sessionID = firstString(input?.sessionID, input?.session_id, eventSessionID(event), ctx?.project?.id);
  return {
    session_id: sessionID,
    turn_id: firstString(input?.messageID, input?.message_id, event?.properties?.messageID, event?.properties?.message_id),
    cwd: firstString(input?.cwd, input?.path?.cwd, ctx?.directory, ctx?.worktree),
    model: modelString(input?.model) || modelString(event?.properties?.info?.model),
    transcript_path: firstString(input?.transcriptPath, input?.transcript_path)
  };
}

function setPath(target, path, value) {
  if (!target || !Array.isArray(path) || path.length === 0) return;
  let cursor = target;
  for (const key of path.slice(0, -1)) {
    if (!cursor[key] || typeof cursor[key] !== "object") cursor[key] = {};
    cursor = cursor[key];
  }
  cursor[path[path.length - 1]] = value;
}

async function applyAdapterResponse(adapterResponse, output, input, ctx) {
  if (!adapterResponse || adapterResponse.adapter_action === "noop") return;
  if (adapterResponse.adapter_action === "throw") {
    const err = new Error(adapterResponse.message || "blocked by Hitch");
    err.hitchAdapterThrow = true;
    throw err;
  }
  if (adapterResponse.adapter_action === "set") {
    if (Array.isArray(adapterResponse.path) && adapterResponse.path.length > 0) {
      setPath(output, adapterResponse.path, adapterResponse.value);
    } else if (adapterResponse.value && typeof adapterResponse.value === "object") {
      Object.assign(output, adapterResponse.value);
    }
    return;
  }
  if (adapterResponse.adapter_action === "append") {
    const path = Array.isArray(adapterResponse.path) ? adapterResponse.path : [];
    if (path.length === 0) return;
    let cursor = output;
    for (const key of path.slice(0, -1)) {
      if (!cursor[key] || typeof cursor[key] !== "object") cursor[key] = {};
      cursor = cursor[key];
    }
    const key = path[path.length - 1];
    if (!Array.isArray(cursor[key])) cursor[key] = [];
    cursor[key].push(adapterResponse.value);
    return;
  }
  if (adapterResponse.adapter_action === "inject_context") {
    const sessionID = firstString(input?.sessionID, input?.session_id);
    if (!sessionID || typeof adapterResponse.value !== "string" || adapterResponse.value.length === 0) return;
    await ctx.client.session.prompt({
      path: { id: sessionID },
      body: {
        noReply: true,
        parts: [{ type: "text", text: adapterResponse.value }]
      }
    });
  }
}

async function postToHitch(endpoint, sourceEventType, input, output, ctx) {
  const event = { input: safeClone(input), output: safeClone(output) };
  const sourcePayload = {
    event,
    metadata: collectMetadata(input, event, ctx)
  };
  try {
    const response = await fetch(hitchAPIURL() + "/v1/events", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        mode: endpoint,
        harness: `)
	b.WriteString(harnessLiteral)
	b.WriteString(`,
        source_event_type: sourceEventType,
        source_payload: sourcePayload,
        hitch_client_version: `)
	b.WriteString(versionLiteral)
	b.WriteString(`
      })
    });
    if (!response.ok || endpoint !== "sync") return;
    const payload = await response.json();
    await applyAdapterResponse(payload, output, input, ctx);
  } catch (err) {
    if (err && err.hitchAdapterThrow) throw err;
  }
}

async function dispatchToHitch(sourceEventType, input, output, ctx) {
  await postToHitch("sync", sourceEventType, input, output, ctx);
}

function observedSourceEventType(event) {
  if (!event || !HITCH_EVENTS.includes(event.type)) return undefined;
  if (event.type !== "message.part.updated") return event.type;
  const part = event?.properties?.part;
  if (part?.type === "step-finish") return "message.part.step-finish";
  if (part?.type === "text" && part?.metadata?.openai?.phase === "final_answer" && typeof part.text === "string" && part.text.length > 0) {
    return "message.part.text";
  }
  return undefined;
}

async function observeWithHitch(sourceEventType, event, ctx) {
  if (!sourceEventType) return;
  const sourcePayload = {
    event: safeClone(event),
    metadata: collectMetadata(event, event, ctx)
  };
  try {
    await fetch(hitchAPIURL() + "/v1/events", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        mode: "async",
        harness: `)
	b.WriteString(harnessLiteral)
	b.WriteString(`,
        source_event_type: sourceEventType,
        source_payload: sourcePayload,
        hitch_client_version: `)
	b.WriteString(versionLiteral)
	b.WriteString(`
      })
    });
  } catch {}
}


export const HitchPlugin = async (ctx) => {
  return {
    event: async ({ event }) => {
      await observeWithHitch(observedSourceEventType(event), event, ctx);
    },
    "chat.message": async (input, output) => dispatchToHitch("chat.message", input, output, ctx),
    "chat.params": async (input, output) => dispatchToHitch("chat.params", input, output, ctx),
    "chat.headers": async (input, output) => dispatchToHitch("chat.headers", input, output, ctx),
    "command.execute.before": async (input, output) => dispatchToHitch("command.execute.before", input, output, ctx),
    "permission.ask": async (input, output) => dispatchToHitch("permission.ask", input, output, ctx),
    "tool.execute.before": async (input, output) => dispatchToHitch("tool.execute.before", input, output, ctx),
    "tool.execute.after": async (input, output) => dispatchToHitch("tool.execute.after", input, output, ctx),
    "tool.definition": async (input, output) => dispatchToHitch("tool.definition", input, output, ctx),
    "shell.env": async (input, output) => dispatchToHitch("shell.env", input, output, ctx),
    "experimental.session.compacting": async (input, output) => dispatchToHitch("experimental.session.compacting", input, output, ctx),
    "experimental.compaction.autocontinue": async (input, output) => dispatchToHitch("experimental.compaction.autocontinue", input, output, ctx),
    "experimental.text.complete": async (input, output) => dispatchToHitch("experimental.text.complete", input, output, ctx),
  };
};
`)
	return []byte(b.String()), nil
}
