package install

import (
	"os"
	"strings"
)

func piExtensionInstalled(path string) bool {
	b, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	content := string(b)
	return strings.Contains(content, piManagedExtensionMarker) && strings.Contains(content, "dispatchToHitch")
}

func installPiExtension(path, backup, apiURL string) error {
	content, err := piExtensionContent(apiURL)
	if err != nil {
		return err
	}
	return installExtensionContent(path, backup, content)
}

func installOMPExtension(path, backup, apiURL string) error {
	content, err := ompExtensionContent(apiURL)
	if err != nil {
		return err
	}
	return installExtensionContent(path, backup, content)
}

func piExtensionContent(apiURL string) ([]byte, error) {
	return extensionContent("pi", "hitch-pi-extension", piExtensionEvents, piExtensionSyncEvents, apiURL)
}

func ompExtensionContent(apiURL string) ([]byte, error) {
	return extensionContent("omp", "hitch-omp-extension", ompExtensionEvents, ompExtensionSyncEvents, apiURL)
}

func extensionContent(harnessName, clientVersion string, sourceEvents, syncEvents []string, apiURL string) ([]byte, error) {
	urlLiteral, err := jsonStringLiteral(apiURL)
	if err != nil {
		return nil, err
	}
	eventsLiteral, err := jsonArrayLiteral(sourceEvents)
	if err != nil {
		return nil, err
	}
	syncEventsLiteral, err := jsonArrayLiteral(syncEvents)
	if err != nil {
		return nil, err
	}
	harnessLiteral, err := jsonStringLiteral(harnessName)
	if err != nil {
		return nil, err
	}
	versionLiteral, err := jsonStringLiteral(clientVersion)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	b.Grow(2700 + len(piManagedExtensionMarker) + len(urlLiteral) + len(eventsLiteral) + len(syncEventsLiteral) + len(harnessLiteral) + len(versionLiteral))
	b.WriteString("// ")
	b.WriteString(piManagedExtensionMarker)
	b.WriteString(`.
// Generated by hitch-client install. Do not edit by hand.

const HITCH_PINNED_API_URL = `)
	b.WriteString(urlLiteral)
	b.WriteString(`;
const HITCH_DEFAULT_API_URL = "http://127.0.0.1:8799";
const HITCH_EVENTS = `)
	b.WriteString(eventsLiteral)
	b.WriteString(`;
const HITCH_SYNC_EVENTS = `)
	b.WriteString(syncEventsLiteral)
	b.WriteString(`;
const HITCH_SYNC_EVENT_SET = new Set(HITCH_SYNC_EVENTS);

function envString(name) {
  const processLike = typeof globalThis === "object" ? Object(globalThis).process : undefined;
  const env = processLike && typeof processLike === "object" ? Object(processLike).env : undefined;
  const value = env && typeof env === "object" ? Object(env)[name] : undefined;
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function hitchAPIURL() {
  return firstString(HITCH_PINNED_API_URL, envString("HITCH_URL"), HITCH_DEFAULT_API_URL);
}

function setPath(target, path, value) {
  if (!target || !Array.isArray(path) || path.length === 0) return;
  let cursor = target;
  for (const key of path.slice(0, -1)) {
    if (!cursor[key] || typeof cursor[key] !== "object") cursor[key] = {};
    cursor = cursor[key];
  }
  cursor[path[path.length - 1]] = value;
}

function applyAdapterResponse(adapterResponse, event) {
  if (!adapterResponse || adapterResponse.adapter_action === "noop") return undefined;
  if (adapterResponse.adapter_action === "return") return adapterResponse.return_value;
  if (adapterResponse.adapter_action === "mutate_and_return") {
    for (const mutation of adapterResponse.mutations || []) {
      setPath(event, mutation.path, mutation.value);
    }
    if (Object.prototype.hasOwnProperty.call(adapterResponse, "return_value")) {
      return adapterResponse.return_value;
    }
  }
  return undefined;
}

function firstString(...values) {
  for (const value of values) {
    if (typeof value === "string" && value.length > 0) return value;
    if (typeof value === "number" && Number.isFinite(value)) return String(value);
  }
  return undefined;
}

function sessionFileFrom(ctx) {
  const manager = ctx?.sessionManager;
  if (!manager) return undefined;
  try {
    if (typeof manager.getSessionFile === "function") return manager.getSessionFile();
  } catch {}
  return firstString(manager.sessionFile, manager.file, manager.path);
}

function sessionIDFrom(event, ctx, transcriptPath) {
  const direct = firstString(event?.session_id, event?.sessionId, ctx?.session_id, ctx?.sessionId);
  if (direct) return direct;
  const manager = ctx?.sessionManager;
  try {
    const id = manager && typeof manager.getSessionId === "function" ? manager.getSessionId() : undefined;
    if (id) return String(id);
  } catch {}
  const fromManager = firstString(manager?.session_id, manager?.sessionId, manager?.id);
  if (fromManager) return fromManager;
  if (typeof transcriptPath === "string" && transcriptPath.length > 0) {
    const name = transcriptPath.split(/[\\/]/).pop() || transcriptPath;
    return name.replace(/\.(jsonl|json)$/i, "");
  }
  return undefined;
}

function modelString(model) {
  if (typeof model === "string") return model;
  if (!model || typeof model !== "object") return undefined;
  const provider = firstString(model.provider, model.providerId, model.vendor);
  const id = firstString(model.id, model.model, model.name);
  if (provider && id) return provider + "/" + id;
  return id || provider;
}

function collectMetadata(event, ctx) {
  const transcriptPath = firstString(event?.transcript_path, event?.transcriptPath, sessionFileFrom(ctx));
  return {
    session_id: sessionIDFrom(event, ctx, transcriptPath),
    turn_id: firstString(event?.turn_id, event?.turnId, event?.turnIndex),
    cwd: firstString(event?.cwd, ctx?.cwd),
    model: firstString(event?.model) || modelString(event?.model) || modelString(ctx?.model),
    transcript_path: transcriptPath
  };
}


async function dispatchToHitch(sourceEventType, event, ctx) {
  let sourcePayload;
  try {
    sourcePayload = {
      event: JSON.parse(JSON.stringify(event ?? {})),
      metadata: collectMetadata(event, ctx)
    };
  } catch {
    return undefined;
  }

  const sync = HITCH_SYNC_EVENT_SET.has(sourceEventType);
  try {
    const response = await fetch(hitchAPIURL() + "/v1/events", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        mode: sync ? "sync" : "async",
        harness: `)
	b.WriteString(harnessLiteral)
	b.WriteString(`,
        source_event_type: sourceEventType,
        source_payload: sourcePayload,
        hitch_client_version: `)
	b.WriteString(versionLiteral)
	b.WriteString(`
      })
    });
    if (!response.ok || !sync) return undefined;
    const payload = await response.json();
    return applyAdapterResponse(payload, event);
  } catch {
    return undefined;
  }
}

export default function(pi) {
  for (const sourceEventType of HITCH_EVENTS) {
    pi.on(sourceEventType, async (event, ctx) => dispatchToHitch(sourceEventType, event, ctx));
  }
}
`)
	return []byte(b.String()), nil
}
